// src/admin/views/NewsForm.vue
<script setup lang="ts">
import { ref, onMounted, watch, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Save, ArrowLeft, Loader2, Lock, Unlock } from 'lucide-vue-next'
import slugify from 'slugify'
import api from '../services/api'
import TipTapEditor from '../components/TipTapEditor.vue'
import ImageUpload from '../components/ImageUpload.vue'
import TagsInput from '../components/TagsInput.vue'
import SEOFields from '../components/SEOFields.vue'

const router = useRouter()
const route = useRoute()
const isEditing = route.params.id !== undefined

const form = ref({
  // Basic fields
  title: '',
  slug: '',
  excerpt: '',
  content: '',
  published: false,

  // Images
  imageUrl: '',
  imageAlt: '',
  capaNova: null,
  ogImage: '',

  // SEO
  metaTitle: '',
  metaDescription: '',
  keywords: '',
  canonicalUrl: '',
  ogTitle: '',
  ogDescription: '',
  twitterCard: 'summary_large_image',

  // Organization
  categoryId: null,
  authorId: null,
  tags: [],
  featuredLevel: 0,
  readingTime: 0
})

const categories = ref([])
const authors = ref([])
const loading = ref(false)
const saving = ref(false)
const slugManuallyEdited = ref(false)

// SEO fields grouped for the component
const seoFields = computed({
  get: () => ({
    metaTitle: form.value.metaTitle,
    metaDescription: form.value.metaDescription,
    keywords: form.value.keywords,
    canonicalUrl: form.value.canonicalUrl,
    ogTitle: form.value.ogTitle,
    ogDescription: form.value.ogDescription,
    ogImage: form.value.ogImage,
    twitterCard: form.value.twitterCard
  }),
  set: (value) => {
    Object.assign(form.value, value)
  }
})

const fetchOptions = async () => {
  try {
    const [categoriesRes, authorsRes] = await Promise.all([
      api.get('/categories'),
      api.get('/authors')
    ])
    categories.value = categoriesRes.data
    authors.value = authorsRes.data
  } catch (error) {
    console.error('Error loading options:', error)
  }
}

const fetchItem = async () => {
  if (!isEditing) return
  loading.value = true
  try {
    const { data } = await api.get(`/news/${route.params.id}`)
    form.value = {
      title: data.title || '',
      slug: data.slug || '',
      excerpt: data.excerpt || '',
      content: data.content || '',
      published: data.published || false,
      imageUrl: data.imageUrl || '',
      imageAlt: data.imageAlt || '',
      capaNova: data.capaNova || null,
      ogImage: data.ogImage || '',
      metaTitle: data.metaTitle || '',
      metaDescription: data.metaDescription || '',
      keywords: data.keywords || '',
      canonicalUrl: data.canonicalUrl || '',
      ogTitle: data.ogTitle || '',
      ogDescription: data.ogDescription || '',
      twitterCard: data.twitterCard || 'summary_large_image',
      categoryId: data.categoryId || null,
      authorId: data.authorId || null,
      tags: data.tags || [],
      featuredLevel: data.featuredLevel || 0,
      readingTime: data.readingTime || 0
    }
  } catch (error) {
    alert('Erro ao carregar notícia')
    router.push('/news')
  } finally {
    loading.value = false
  }
}

const autoSlug = () => {
  if (slugManuallyEdited.value || isEditing) return
  form.value.slug = slugify(form.value.title, {
    lower: true,
    strict: true,
    locale: 'pt'
  })
}

const toggleSlugLock = () => {
  slugManuallyEdited.value = !slugManuallyEdited.value
  if (!slugManuallyEdited.value) {
    autoSlug()
  }
}

const calculateReadingTime = () => {
  const text = form.value.content.replace(/<[^>]*>/g, '')
  const words = text.trim().split(/\s+/).filter(word => word.length > 0).length
  form.value.readingTime = Math.ceil(words / 200)
}

watch(() => form.value.content, calculateReadingTime)

const save = async () => {
  if (!form.value.title.trim()) {
    alert('Título é obrigatório')
    return
  }
  if (!form.value.slug.trim()) {
    alert('Slug é obrigatório')
    return
  }

  saving.value = true
  calculateReadingTime()

  try {
    const now = new Date().toISOString()
    const payload = {
      ...form.value,
      updatedAt: now,
      publishedAt: form.value.published ? (form.value.publishedAt || now) : null
    }

    if (isEditing) {
      await api.patch(`/news/${route.params.id}`, payload)
    } else {
      await api.post('/news', payload)
    }

    router.push('/news')
  } catch (error: any) {
    alert('Erro ao salvar: ' + (error.response?.data?.error || error.message))
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  fetchOptions()
  fetchItem()
})
</script>

<template>
  <div class="space-y-8 max-w-5xl mx-auto pb-10">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-4">
        <button @click="router.back()" class="p-2 hover:bg-neutral-100 rounded-full transition-colors">
          <ArrowLeft :size="20" />
        </button>
        <div>
          <h3 class="text-3xl font-black tracking-tighter uppercase italic">
            {{ isEditing ? 'Editar Notícia' : 'Nova Notícia' }}
          </h3>
          <p class="text-neutral-500 font-medium">Preencha os campos abaixo para publicar.</p>
        </div>
      </div>
      <button
        @click="save"
        :disabled="saving"
        class="flex items-center gap-2 px-8 py-3 bg-black text-white rounded-full font-bold text-sm shadow-xl shadow-black/20 hover:scale-105 transition-all active:scale-95 disabled:opacity-50"
      >
        <Loader2 v-if="saving" class="animate-spin" :size="18" />
        <Save v-else :size="18" />
        {{ saving ? 'Salvando...' : 'Salvar Notícia' }}
      </button>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="py-20 flex justify-center">
      <Loader2 class="animate-spin text-neutral-300" :size="48" />
    </div>

    <!-- Form -->
    <div v-else class="space-y-6">
      <!-- Basic Information -->
      <div class="bg-white p-8 rounded-3xl border border-neutral-200 shadow-sm space-y-6">
        <h4 class="text-xs font-black uppercase tracking-widest text-neutral-600">Informações Básicas</h4>

        <!-- Title -->
        <div class="space-y-2">
          <label class="text-[10px] font-black uppercase tracking-widest text-neutral-400">Título da Notícia</label>
          <input
            v-model="form.title"
            @input="autoSlug"
            type="text"
            placeholder="Ex: O futuro do aço inox..."
            class="w-full px-4 py-3 bg-neutral-50 rounded-xl border-none focus:ring-2 focus:ring-black outline-none font-bold text-lg"
          >
        </div>

        <!-- Slug with Lock -->
        <div class="space-y-2">
          <label class="text-[10px] font-black uppercase tracking-widest text-neutral-400">Slug (URL)</label>
          <div class="flex gap-2">
            <input
              v-model="form.slug"
              type="text"
              placeholder="o-futuro-do-aco-inox"
              :disabled="!isEditing && !slugManuallyEdited"
              class="flex-1 px-4 py-3 bg-neutral-50 rounded-xl border-none focus:ring-2 focus:ring-black outline-none font-medium text-sm text-neutral-500 disabled:opacity-50"
            >
            <button
              v-if="!isEditing"
              type="button"
              @click="toggleSlugLock"
              class="px-4 py-3 bg-neutral-100 hover:bg-neutral-200 rounded-xl transition-colors"
              :title="slugManuallyEdited ? 'Desbloquear (auto-gerar)' : 'Bloquear (edição manual)'"
            >
              <Lock v-if="!slugManuallyEdited" :size="18" />
              <Unlock v-else :size="18" />
            </button>
          </div>
        </div>

        <!-- Excerpt -->
        <div class="space-y-2">
          <label class="text-[10px] font-black uppercase tracking-widest text-neutral-400">Resumo (Excerpt)</label>
          <textarea
            v-model="form.excerpt"
            rows="3"
            placeholder="Uma breve descrição para a listagem..."
            class="w-full px-4 py-3 bg-neutral-50 rounded-xl border-none focus:ring-2 focus:ring-black outline-none font-medium text-sm"
          ></textarea>
        </div>
      </div>

      <!-- Featured Image -->
      <div class="bg-white p-8 rounded-3xl border border-neutral-200 shadow-sm">
        <h4 class="text-xs font-black uppercase tracking-widest text-neutral-600 mb-6">Imagem Destaque</h4>
        <ImageUpload
          v-model="form.imageUrl"
          v-model:altValue="form.imageAlt"
          label="Imagem Principal"
          folder="inox-link/news"
          :showAlt="true"
        />
      </div>

      <!-- Content Editor -->
      <div class="bg-white p-8 rounded-3xl border border-neutral-200 shadow-sm">
        <h4 class="text-xs font-black uppercase tracking-widest text-neutral-600 mb-6">Conteúdo</h4>
        <TipTapEditor
          v-model="form.content"
          placeholder="Escreva o conteúdo da notícia aqui..."
        />
      </div>

      <!-- Organization -->
      <div class="bg-white p-8 rounded-3xl border border-neutral-200 shadow-sm space-y-6">
        <h4 class="text-xs font-black uppercase tracking-widest text-neutral-600">Organização</h4>

        <div class="grid grid-cols-2 gap-4">
          <!-- Category -->
          <div class="space-y-2">
            <label class="text-[10px] font-black uppercase tracking-widest text-neutral-400">Categoria</label>
            <select
              v-model="form.categoryId"
              class="w-full px-4 py-3 bg-neutral-50 rounded-xl border-none focus:ring-2 focus:ring-black outline-none font-medium text-sm"
            >
              <option :value="null">Selecione uma categoria</option>
              <option v-for="cat in categories" :key="cat.id" :value="cat.id">
                {{ cat.name }}
              </option>
            </select>
          </div>

          <!-- Author -->
          <div class="space-y-2">
            <label class="text-[10px] font-black uppercase tracking-widest text-neutral-400">Autor</label>
            <select
              v-model="form.authorId"
              class="w-full px-4 py-3 bg-neutral-50 rounded-xl border-none focus:ring-2 focus:ring-black outline-none font-medium text-sm"
            >
              <option :value="null">Selecione um autor</option>
              <option v-for="author in authors" :key="author.id" :value="author.id">
                {{ author.name }}
              </option>
            </select>
          </div>
        </div>

        <!-- Tags -->
        <TagsInput v-model="form.tags" />

        <!-- Featured Level -->
        <div class="space-y-2">
          <label class="text-[10px] font-black uppercase tracking-widest text-neutral-400">Nível de Destaque</label>
          <input
            v-model.number="form.featuredLevel"
            type="number"
            min="0"
            max="3"
            placeholder="0 = Normal, 1-3 = Níveis de destaque"
            class="w-full px-4 py-3 bg-neutral-50 rounded-xl border-none focus:ring-2 focus:ring-black outline-none font-medium text-sm"
          />
          <p class="text-xs text-neutral-500">0 = Normal, 1 = Destaque baixo, 2 = Destaque médio, 3 = Destaque alto</p>
        </div>
      </div>

      <!-- SEO -->
      <SEOFields
        v-model="seoFields"
        :mainTitle="form.title"
        :mainExcerpt="form.excerpt"
      />

      <!-- Additional Images -->
      <details class="bg-white border border-neutral-200 rounded-3xl overflow-hidden">
        <summary class="px-6 py-4 cursor-pointer font-black uppercase text-xs tracking-widest text-neutral-600 hover:bg-neutral-50 transition-colors">
          Imagens Adicionais
        </summary>
        <div class="px-6 pb-6">
          <ImageUpload
            v-model="form.capaNova"
            label="Capa Nova"
            folder="inox-link/capa"
            :showAlt="false"
          />
        </div>
      </details>

      <!-- Publish Settings -->
      <div class="bg-white p-8 rounded-3xl border border-neutral-200 shadow-sm">
        <h4 class="text-xs font-black uppercase tracking-widest text-neutral-600 mb-6">Publicação</h4>
        <div class="flex items-center gap-3 p-4 bg-neutral-50 rounded-2xl">
          <input
            v-model="form.published"
            type="checkbox"
            id="published"
            class="w-5 h-5 accent-black cursor-pointer"
          >
          <label for="published" class="font-bold text-sm cursor-pointer select-none">Publicar imediatamente</label>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/admin/NewsForm.tsx
import React, { useState } from 'react';
import { actions } from 'astro:actions';
import Editor from './Editor';
import ImageUpload from './ImageUpload';
import SEOAnalyzer from './SEOAnalyzer';
import { aiService } from '../../services/ai';
import { Save, Loader2, Globe, FileText, Layout, Eye, ArrowLeft, Search, Sparkles } from 'lucide-react';


import { cn } from '../../scripts/utils';

interface NewsFormProps {
    initialData?: any;
    categories: any[];
    authors: any[];
}

export default function NewsForm({ initialData, categories, authors }: NewsFormProps) {
    const [loading, setLoading] = useState(false);
    const [aiSuggesting, setAiSuggesting] = useState(false);
    const [formData, setFormData] = useState({

        title: initialData?.title || '',
        slug: initialData?.slug || '',
        content: initialData?.content || '',
        excerpt: initialData?.excerpt || '',
        imageUrl: initialData?.imageUrl || '',
        categoryId: initialData?.categoryId || (categories[0]?.id || null),
        authorId: initialData?.authorId || (authors[0]?.id || null),
        published: initialData?.published || false,
        metaTitle: initialData?.metaTitle || '',
        metaDescription: initialData?.metaDescription || '',
        keywords: initialData?.keywords || '',
    });


    const generateSlug = (title: string) => {
        return title.toLowerCase()
            .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/(^-|-$)+/g, '');
    };

    const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const title = e.target.value;
        setFormData(prev => ({
            ...prev,
            title,
            slug: prev.slug === generateSlug(prev.title) ? generateSlug(title) : prev.slug
        }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);

        try {
            let result;
            if (initialData?.id) {
                result = await actions.updateNews({ id: initialData.id, ...formData });
            } else {
                result = await actions.createNews(formData);
            }

            const { error } = result;

            if (error) {
                alert('Erro: ' + error.message);
            } else {
                window.location.href = '/admin/news';
            }
        } catch (err) {
            console.error(err);
            alert('Erro inesperado');
        } finally {
            setLoading(false);
        }
    };

    const handleAiSuggest = async () => {
        if (!formData.content || formData.content.length < 50) {
            alert('Escreva um pouco mais de conteúdo para que a IA possa analisar.');
            return;
        }

        setAiSuggesting(true);
        try {
            const suggestion = await aiService.suggestMetadata(formData.content, formData.title);
            setFormData(prev => ({
                ...prev,
                metaTitle: suggestion.title,
                metaDescription: suggestion.description,
                keywords: suggestion.keywords
            }));
        } catch (err) {
            alert('Falha ao obter sugestão da IA.');
        } finally {
            setAiSuggesting(false);
        }
    };


    return (
        <form onSubmit={handleSubmit} className="flex flex-col lg:flex-row min-h-screen bg-[#fcfcfc]">
            {/* Main Canvas */}
            <div className="flex-1 flex justify-center py-12 px-6 lg:px-12 bg-white min-h-screen border-r border-zinc-100 shadow-sm">
                <div className="w-full max-w-[800px] space-y-10">
                    <header className="flex items-center gap-3 text-zinc-400 mb-8">
                        <a href="/admin/news" className="hover:text-black transition-colors flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider">
                            <ArrowLeft size={14} /> Painel
                        </a>
                        <span className="text-zinc-200">/</span>
                        <span className="text-[11px] font-bold uppercase tracking-wider text-zinc-400">{initialData?.id ? 'Editar' : 'Escrever'}</span>
                    </header>

                    <section className="space-y-6">
                        <input
                            type="text"
                            value={formData.title}
                            onChange={handleTitleChange}
                            required
                            placeholder="Adicione um título"
                            className="w-full bg-transparent border-none text-5xl lg:text-6xl font-bold tracking-tight text-zinc-900 placeholder:text-zinc-100 focus:outline-none focus:ring-0 p-0 leading-tight"
                        />

                        <div className="flex gap-6 border-b border-zinc-50 pb-8">
                            <div className="flex-1">
                                <label className="text-[10px] font-bold text-zinc-300 uppercase tracking-widest mb-2 block">Resumo do post</label>
                                <textarea
                                    value={formData.excerpt}
                                    onChange={(e) => setFormData(prev => ({ ...prev, excerpt: e.target.value }))}
                                    rows={2}
                                    placeholder="Uma breve introdução..."
                                    className="w-full bg-transparent border-none p-0 text-zinc-500 placeholder:text-zinc-200 focus:ring-0 outline-none text-lg leading-relaxed resize-none font-light italic"
                                />
                            </div>
                        </div>
                    </section>

                    <div className="pb-32">
                        <Editor
                            content={formData.content}
                            onChange={(content) => setFormData(prev => ({ ...prev, content }))}
                        />
                    </div>
                </div>
            </div>

            {/* Gutenberg Sidebar */}
            <aside className="w-full lg:w-80 bg-[#fcfcfc] sticky top-0 h-screen overflow-y-auto p-0 border-l border-zinc-100">
                <div className="p-6 space-y-8">
                    <div className="flex items-center justify-between pb-4 border-b border-zinc-100">
                        <h3 className="text-[11px] font-bold text-zinc-400 uppercase tracking-widest">Configurações</h3>
                        <div className="flex gap-2">
                            <button
                                type="submit"
                                disabled={loading}
                                className="px-4 py-2 bg-black text-white text-[10px] font-bold uppercase tracking-wider rounded-lg shadow-lg hover:bg-zinc-800 transition-all flex items-center gap-2"
                            >
                                {loading ? <Loader2 className="animate-spin" size={12} /> : <Save size={12} />}
                                {initialData?.id ? 'Atualizar' : 'Publicar'}
                            </button>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <section className="space-y-4">
                            <h4 className="text-[11px] font-bold text-zinc-900 uppercase tracking-wider flex items-center gap-2">
                                <Globe size={14} className="text-zinc-400" /> Visibilidade
                            </h4>

                            <div className="flex bg-zinc-100 p-1 rounded-xl">
                                <button
                                    type="button"
                                    onClick={() => setFormData(prev => ({ ...prev, published: false }))}
                                    className={cn(
                                        "flex-1 py-2 rounded-lg text-[10px] font-bold uppercase transition-all",
                                        !formData.published ? "bg-white text-zinc-900 shadow-sm" : "text-zinc-400"
                                    )}
                                >
                                    Rascunho
                                </button>
                                <button
                                    type="button"
                                    onClick={() => setFormData(prev => ({ ...prev, published: true }))}
                                    className={cn(
                                        "flex-1 py-2 rounded-lg text-[10px] font-bold uppercase transition-all",
                                        formData.published ? "bg-black text-white shadow-sm" : "text-zinc-400"
                                    )}
                                >
                                    Público
                                </button>
                            </div>
                        </section>

                        <section className="space-y-4">
                            <h4 className="text-[11px] font-bold text-zinc-900 uppercase tracking-wider flex items-center gap-2">
                                <Layout size={14} className="text-zinc-400" /> Taxonomia
                            </h4>

                            <div className="space-y-4">
                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Categoria</label>
                                    <select
                                        value={formData.categoryId || ''}
                                        onChange={(e) => setFormData(prev => ({ ...prev, categoryId: Number(e.target.value) }))}
                                        className="w-full bg-white border border-zinc-200 rounded-lg px-3 py-2 text-xs font-bold text-zinc-900 outline-none"
                                    >
                                        {categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                                    </select>
                                </div>

                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Autor</label>
                                    <select
                                        value={formData.authorId || ''}
                                        onChange={(e) => setFormData(prev => ({ ...prev, authorId: Number(e.target.value) }))}
                                        className="w-full bg-white border border-zinc-200 rounded-lg px-3 py-2 text-xs font-bold text-zinc-900 outline-none"
                                    >
                                        {authors.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                                    </select>
                                </div>
                            </div>
                        </section>

                        <section className="space-y-4">
                            <ImageUpload
                                label="Imagem de Destaque"
                                value={formData.imageUrl}
                                onChange={(url) => setFormData(prev => ({ ...prev, imageUrl: url }))}
                            />
                        </section>

                        <section className="space-y-4">
                            <div className="flex items-center justify-between">
                                <h4 className="text-[11px] font-bold text-zinc-900 uppercase tracking-wider flex items-center gap-2">
                                    <Search size={14} className="text-zinc-400" /> Metadados SEO
                                </h4>
                                <button
                                    type="button"
                                    onClick={handleAiSuggest}
                                    disabled={aiSuggesting}
                                    className="flex items-center gap-1.5 px-2 py-1 bg-emerald-50 text-emerald-700 rounded-lg text-[9px] font-black uppercase tracking-widest hover:bg-emerald-100 transition-colors disabled:opacity-50"
                                >
                                    {aiSuggesting ? <Loader2 size={10} className="animate-spin" /> : <Sparkles size={10} />}
                                    Sugerir com IA
                                </button>
                            </div>


                            <div className="space-y-4">
                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Título SEO (Opcional)</label>
                                    <input
                                        type="text"
                                        value={formData.metaTitle}
                                        onChange={(e) => setFormData(prev => ({ ...prev, metaTitle: e.target.value }))}
                                        placeholder={formData.title}
                                        className="w-full bg-white border border-zinc-200 rounded-lg px-3 py-2 text-xs font-bold text-zinc-900 outline-none"
                                    />
                                </div>

                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Meta Descrição</label>
                                    <textarea
                                        value={formData.metaDescription}
                                        onChange={(e) => setFormData(prev => ({ ...prev, metaDescription: e.target.value }))}
                                        rows={3}
                                        className="w-full bg-white border border-zinc-200 rounded-lg px-3 py-2 text-xs font-medium text-zinc-600 outline-none resize-none"
                                    />
                                </div>
                            </div>
                        </section>

                        <SEOAnalyzer
                            content={formData.content}
                            title={formData.metaTitle || formData.title}
                            description={formData.metaDescription || formData.excerpt}
                            focusKeyword={formData.keywords}
                            onKeywordChange={(val) => setFormData(prev => ({ ...prev, keywords: val }))}
                        />

                        <section className="space-y-2">
                            <label className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Link Permanente</label>
                            <div className="bg-zinc-100 rounded-lg px-3 py-2 text-[10px] font-mono text-zinc-500 break-all">
                                inoxlink.com.br/news/{formData.slug}
                            </div>
                        </section>
                    </div>



                    <div className="pt-8 flex flex-col gap-3">
                        <button type="button" className="w-full py-3 border border-zinc-200 hover:bg-zinc-50 text-zinc-400 rounded-xl font-bold text-[10px] uppercase tracking-wider transition-all flex items-center justify-center gap-2">
                            <Eye size={14} /> Visualizar Prévia
                        </button>
                    </div>
                </div>
            </aside>
        </form >
    );
}
